apiVersion: v1
kind: Service
metadata:
  name: {{ include "unsloth.fullname" . }}-studio
  labels:
    {{- include "unsloth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.studio.type }}
  sessionAffinity: {{ .Values.services.studio.sessionAffinity }}
  ports:
    - port: {{ .Values.services.studio.port }}
      targetPort: studio
      protocol: TCP
      name: studio
  selector:
    {{- include "unsloth.selectorLabels" . | nindent 4 }}
