healthCheckTimeout: 300
logRequests: true
metricsMaxInMemory: 1000

models:
  "qwen2.5":
    proxy: "http://127.0.0.1:9999"
    cmd: >
      /app/llama-server
      -hfr bartowski/Qwen2.5-0.5B-Instruct-GGUF
      -hff Qwen2.5-0.5B-Instruct-Q4_K_M.gguf
      --port 9999

  "smollm2":
    proxy: "http://127.0.0.1:9999"
    cmd: >
      /app/llama-server
      -hfr bartowski/SmolLM2-135M-Instruct-GGUF
      -hff SmolLM2-135M-Instruct-Q4_K_M.gguf
      --port 9999
